train_file: data/toy
dev_file: data/toy

experiment_dir: ${EXP_DIR}/toy
generate_empty_subdir: true

cell_type: LSTM
hidden_size: 8
src_embedding_size: 30
tgt_embedding_size: 30
encoder_n_layers: 2
decoder_n_layers: 1
eval_batch_size: 1
dropout: 0.2
train_schedule:
    - {lr: 0.001, epochs: 2, batch_size: 1}
    - {lr: 0.0001, epochs: 4, batch_size: 2}

toy_eval: [abc, eg]
